development: &default
  adapter: postgresql
  database: sample_development
  pool: 5
  encoding: unicode

test: &test
  <<: *default
  database: sample_test
  min_messages: warning

cucumber:
  <<: *test
